# PyTorch Full Tutorial 
Is notebook me hum PyTorch ke basic se advanced methods seekhenge.

In [1]:
# 1. Import torch
# PyTorch library import karte hain
import torch

In [2]:
# 2. Tensor banana
# Tensor ek data structure hai (array jaisa)
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [3]:
# Zeros, Ones, Random tensor
print(torch.zeros(3))  # sab 0
print(torch.ones(3))   # sab 1
print(torch.rand(3))   # random values

tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([0.7907, 0.7154, 0.4271])


In [4]:
# 3. Shape check karna
print(x.shape)

torch.Size([3])


In [5]:
# 4. Mathematical operations
a = torch.tensor([1,2])
b = torch.tensor([3,4])

print(a + b)   # addition
print(a * b)   # multiplication

tensor([4, 6])
tensor([3, 8])


In [6]:
# Matrix multiplication
m1 = torch.rand(2,2)
m2 = torch.rand(2,2)
print(torch.matmul(m1, m2))

tensor([[0.0605, 0.0050],
        [0.4393, 0.0807]])


In [7]:
# 5. Autograd (gradient calculation)
x = torch.tensor(2.0, requires_grad=True)
y = x * x
y.backward()
print(x.grad)  # dy/dx

tensor(4.)


In [8]:
# 6. Neural Network banana
import torch.nn as nn

model = nn.Linear(2,1)
print(model)

Linear(in_features=2, out_features=1, bias=True)


In [9]:
# 7. Loss Function
loss_fn = nn.MSELoss()

In [10]:
# 8. Optimizer
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [11]:
# 9. Training Loop
x = torch.randn(10,2)
y = torch.randn(10,1)

for epoch in range(5):
    optimizer.zero_grad()  # gradients reset
    output = model(x)      # forward pass
    loss = loss_fn(output, y)  # loss calculate
    loss.backward()        # backward pass
    optimizer.step()       # update weights
    print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 1.7604618072509766
Epoch 1, Loss: 1.734767198562622
Epoch 2, Loss: 1.71047842502594
Epoch 3, Loss: 1.6874945163726807
Epoch 4, Loss: 1.665722131729126
